apiVersion: v1
kind: Service
metadata:
  name: iventoy
spec:
  type: ClusterIP
  ports:
    - name: iventoy
      port: 80
      targetPort: 26000
      protocol: TCP
  selector:
    app: iventoy